/**
 * Track data for the audio player
 * Enhanced with comprehensive metadata for playlist features
 * Version: 2.0 - Full playlist support with auto-generated filters
 */

window.tracksData = {
    // Track information with comprehensive metadata
    tracks: [
        {
            id: "track_001",
            title: "Softer for J",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220211-16edo-Softer.mp3",
            year: 2022,
            genre: ["Modern Piano", "Experimental"],
            tuning: "16-tone equal temperament",
            mood: ["contemplative", "experimental"],
            tags: ["microtonal", "piano", "ambient"],
            duration: null, // Will be populated when loaded
            album: "Microtonal Explorations",
            bpm: 80,
            key: "C (16-EDO)",
            instruments: ["piano", "synthesizer"],
            description: "A softer piece composed in 16 equal divisions of the octave",
            dateAdded: "2022-02-11",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null, // For future waveform visualization
            analysisData: null  // For future music theory analysis
        },        {
            id: "track_002",
            title: "Quarter-Tone Piano Miniature 1",
            artist: "Nick Vuci", 
            file: "music/NV-20201021-24EDO-SoloPianoMiniature1.flac",
            year: 2020,
            genre: ["Classical Piano", "Minimalist"],
            tuning: "24-tone equal temperament",
            mood: ["meditative", "peaceful"],
            tags: ["microtonal", "piano", "classical", "miniature"],
            duration: null, // Will be populated when loaded
            album: "Quarter-Tone Piano Miniatures",
            bpm: 72,
            key: "A minor (24-EDO)",
            instruments: ["piano"],
            description: "A solo piano miniature composed in 24 equal divisions of the octave",
            dateAdded: "2020-10-21",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_003",
            title: "Mavila 7 Studies: 1. Anti-Ionian",
            artist: "Nick Vuci",
            file: "music/20210511-16EDO-Mavila7Studies_1_AntiIonian.mp3",
            year: 2021,
            genre: ["Modern Piano", "Experimental", "Microtonal Studies"],
            tuning: "16-tone equal temperament",
            mood: ["academic", "exploratory"],
            tags: ["microtonal", "piano", "mavila", "anti-ionian"],
            duration: null,
            album: "Mavila 7 Studies",
            bpm: 85,
            key: "Anti-Ionian (16-EDO)",
            instruments: ["piano"],
            description: "Study exploring the Anti-Ionian mode in 16-EDO using Mavila temperament concepts",
            dateAdded: "2021-05-11",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_004",
            title: "Mavila 7 Studies: 1a. Anti-Ionian Tetrads",
            artist: "Nick Vuci",
            file: "music/20210511-16EDO-Mavila7Studies_1a_AntiIonianTetrads.mp3",
            year: 2021,
            genre: ["Modern Piano", "Experimental", "Jazz Harmony"],
            tuning: "16-tone equal temperament",
            mood: ["academic", "complex"],
            tags: ["microtonal", "piano", "mavila", "jazz", "tetrads"],
            duration: null,
            album: "Mavila 7 Studies",
            bpm: 80,
            key: "Anti-Ionian (16-EDO)",
            instruments: ["piano"],
            description: "Study exploring tetrad (four-note chord) harmony in the Anti-Ionian mode using 16-EDO",
            dateAdded: "2021-05-11",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_005",
            title: "Mavila 7 Studies: 2. Anti-Dorian",
            artist: "Nick Vuci",
            file: "music/20210511-16EDO-Mavila7Studies_2_AntiDorian.mp3",
            year: 2021,
            genre: ["Modern Piano", "Experimental", "Microtonal Studies"],
            tuning: "16-tone equal temperament",
            mood: ["contemplative", "exploratory"],
            tags: ["microtonal", "piano", "mavila", "anti-dorian"],
            duration: null,
            album: "Mavila 7 Studies",
            bpm: 82,
            key: "Anti-Dorian (16-EDO)",
            instruments: ["piano"],
            description: "Study exploring the Anti-Dorian mode in 16-EDO using Mavila temperament concepts",
            dateAdded: "2021-05-11",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_006",
            title: "Mavila 7 Studies: 3. Anti-Phrygian",
            artist: "Nick Vuci",
            file: "music/20210511-16EDO-Mavila7Studies_3_AntiPhrygian.mp3",
            year: 2021,
            genre: ["Modern Piano", "Experimental", "Microtonal Studies"],
            tuning: "16-tone equal temperament",
            mood: ["mysterious", "tense"],
            tags: ["microtonal", "piano", "mavila", "anti-phrygian"],
            duration: null,
            album: "Mavila 7 Studies",
            bpm: 78,
            key: "Anti-Phrygian (16-EDO)",
            instruments: ["piano"],
            description: "Study exploring the Anti-Phrygian mode in 16-EDO using Mavila temperament concepts",
            dateAdded: "2021-05-11",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_007",
            title: "Mavila 7 Studies: 4. Anti-Lydian",
            artist: "Nick Vuci",
            file: "music/20210511-16EDO-Mavila7Studies_4_AntiLydian.mp3",
            year: 2021,
            genre: ["Modern Piano", "Experimental", "Microtonal Studies"],
            tuning: "16-tone equal temperament",
            mood: ["bright", "exploratory"],
            tags: ["microtonal", "piano", "mavila", "anti-lydian"],
            duration: null,
            album: "Mavila 7 Studies",
            bpm: 84,
            key: "Anti-Lydian (16-EDO)",
            instruments: ["piano"],
            description: "Study exploring the Anti-Lydian mode in 16-EDO using Mavila temperament concepts",
            dateAdded: "2021-05-11",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_008",
            title: "Mavila 7 Studies: 5. Anti-Mixolydian",
            artist: "Nick Vuci",
            file: "music/20210511-16EDO-Mavila7Studies_5_AntiMixolydian.mp3",
            year: 2021,
            genre: ["Modern Piano", "Experimental", "Microtonal Studies"],
            tuning: "16-tone equal temperament",
            mood: ["energetic", "playful"],
            tags: ["microtonal", "piano", "mavila", "anti-mixolydian"],
            duration: null,
            album: "Mavila 7 Studies",
            bpm: 86,
            key: "Anti-Mixolydian (16-EDO)",
            instruments: ["piano"],
            description: "Study exploring the Anti-Mixolydian mode in 16-EDO using Mavila temperament concepts",
            dateAdded: "2021-05-11",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_009",
            title: "Mavila 7 Studies: 6. Anti-Aeolian",
            artist: "Nick Vuci",
            file: "music/20210511-16EDO-Mavila7Studies_6_AntiAeolian.mp3",
            year: 2021,
            genre: ["Modern Piano", "Experimental", "Microtonal Studies"],
            tuning: "16-tone equal temperament",
            mood: ["melancholic", "reflective"],
            tags: ["microtonal", "piano", "mavila", "anti-aeolian"],
            duration: null,
            album: "Mavila 7 Studies",
            bpm: 76,
            key: "Anti-Aeolian (16-EDO)",
            instruments: ["piano"],
            description: "Study exploring the Anti-Aeolian mode in 16-EDO using Mavila temperament concepts",
            dateAdded: "2021-05-11",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_010",
            title: "Mavila 7 Studies: 7. Anti-Locrian",
            artist: "Nick Vuci",
            file: "music/20210511-16EDO-Mavila7Studies_7_AntiLocrian.mp3",
            year: 2021,
            genre: ["Modern Piano", "Experimental", "Microtonal Studies"],
            tuning: "16-tone equal temperament",
            mood: ["tense", "dissonant"],
            tags: ["microtonal", "piano", "mavila", "anti-locrian"],
            duration: null,
            album: "Mavila 7 Studies",
            bpm: 80,
            key: "Anti-Locrian (16-EDO)",
            instruments: ["piano"],
            description: "Study exploring the Anti-Locrian mode in 16-EDO using Mavila temperament concepts",
            dateAdded: "2021-05-11",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_011",
            title: "Mavila 7 Studies: Modulation Study",
            artist: "Nick Vuci",
            file: "music/20210515-16EDO-Mavila7Studies_ModulationStudy.mp3",
            year: 2021,
            genre: ["Modern Piano", "Experimental", "Microtonal Studies"],
            tuning: "16-tone equal temperament",
            mood: ["evolving", "complex"],
            tags: ["microtonal", "piano", "mavila", "modulation"],
            duration: null,
            album: "Mavila 7 Studies",
            bpm: 84,
            key: "Multiple (16-EDO)",
            instruments: ["piano"],
            description: "Study exploring modulation between different Mavila modes in 16-EDO",
            dateAdded: "2021-05-15",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_012",
            title: "Mavila 7 Studies: Modulation Study 2",
            artist: "Nick Vuci",
            file: "music/20210515-16EDO-Mavila7Studies_ModulationStudy2.mp3",
            year: 2021,
            genre: ["Modern Piano", "Experimental", "Microtonal Studies"],
            tuning: "16-tone equal temperament",
            mood: ["evolving", "dynamic"],
            tags: ["microtonal", "piano", "mavila", "modulation"],
            duration: null,
            album: "Mavila 7 Studies",
            bpm: 82,
            key: "Multiple (16-EDO)",
            instruments: ["piano"],
            description: "Second study exploring more complex modulation between Mavila modes in 16-EDO",
            dateAdded: "2021-05-15",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_013",
            title: "Solo Piano in 12-NEJI-32",
            artist: "Nick Vuci",
            file: "music/20210516-12NEJI32-SoloPiano.mp3",
            year: 2021,
            genre: ["Classical Piano", "Experimental", "Neji Temperament"],
            tuning: "12-NEJI-32",
            mood: ["serene", "experimental"],
            tags: ["microtonal", "piano", "neji"],
            duration: null,
            album: "Neji Temperament Studies",
            bpm: 76,
            key: "NEJI Scale",
            instruments: ["piano"],
            description: "Piano composition using the 12-NEJI-32 temperament system, combining integer-limit just intonation with EDO concepts",
            dateAdded: "2021-05-16",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_014",
            title: "Mavila Beat",
            artist: "Nick Vuci",
            file: "music/20210516-16EDO-MavilaBeat.mp3",
            year: 2021,
            genre: ["Electronic", "Experimental", "Microtonal Beat"],
            tuning: "16-tone equal temperament",
            mood: ["energetic", "rhythmic"],
            tags: ["microtonal", "electronic", "mavila", "beat"],
            duration: null,
            album: "Microtonal Beats",
            bpm: 92,
            key: "Mavila Mode (16-EDO)",
            instruments: ["synthesizer", "drums", "bass"],
            description: "Electronic beat composition utilizing Mavila temperament in 16-EDO",
            dateAdded: "2021-05-16",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_015",
            title: "Overtone Scale Song",
            artist: "Nick Vuci",
            file: "music/20210516-24NEJI128-OvertoneScaleSong.mp3",
            year: 2021,
            genre: ["Ambient", "Experimental", "Overtone Music"],
            tuning: "24-NEJI-128",
            mood: ["ethereal", "peaceful"],
            tags: ["microtonal", "overtone", "neji", "ambient"],
            duration: null,
            album: "Overtone Series Studies",
            bpm: 68,
            key: "Overtone Scale",
            instruments: ["synthesizer", "vocals"],
            description: "Ambient composition using overtone series scales in 24-NEJI-128 temperament",
            dateAdded: "2021-05-16",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_016",
            title: "Piano Quintet Movement 2 (Exposition Sketch)",
            artist: "Nick Vuci",
            file: "music/20210524-4567CrossSet-Piano_Quintet_mvmt2_expositionSketch.mp3",
            year: 2021,
            genre: ["Chamber Music", "Contemporary Classical"],
            tuning: "4567 Cross Set",
            mood: ["dramatic", "complex"],
            tags: ["microtonal", "chamber", "piano quintet", "cross set"],
            duration: null,
            album: "Piano Quintet in Cross Set Temperament",
            bpm: 88,
            key: "Cross Set Tonality",
            instruments: ["piano", "violin", "viola", "cello"],
            description: "Exposition sketch for the second movement of a piano quintet using 4567 Cross Set temperament",
            dateAdded: "2021-05-24",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_017",
            title: "Serialism Chords",
            artist: "Nick Vuci",
            file: "music/20210526-16NEJI128-SerialismChords.mp3",
            year: 2021,
            genre: ["Serialist", "Experimental", "Contemporary Classical"],
            tuning: "16-NEJI-128",
            mood: ["dissonant", "structured"],
            tags: ["microtonal", "serialism", "neji", "contemporary"],
            duration: null,
            album: "Microtonal Serialism Studies",
            bpm: 60,
            key: "Serialist (16-NEJI-128)",
            instruments: ["synthesizer", "piano"],
            description: "Exploration of serial techniques using chord progressions in 16-NEJI-128 temperament",
            dateAdded: "2021-05-26",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_018",
            title: "Serialism Dubstep Sketch",
            artist: "Nick Vuci",
            file: "music/20210526-16NEJI128-SerialismDubstepSketch.mp3",
            year: 2021,
            genre: ["Electronic", "Dubstep", "Experimental"],
            tuning: "16-NEJI-128",
            mood: ["intense", "dark"],
            tags: ["microtonal", "serialism", "dubstep", "electronic"],
            duration: null,
            album: "Microtonal Dubstep",
            bpm: 140,
            key: "Serialist (16-NEJI-128)",
            instruments: ["synthesizer", "drums", "bass"],
            description: "Fusion of serialist compositional techniques with dubstep production in 16-NEJI-128 temperament",
            dateAdded: "2021-05-26",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_019",
            title: "Tone Row",
            artist: "Nick Vuci",
            file: "music/20210526-16NEJI128-ToneRow.mp3",
            year: 2021,
            genre: ["Serialist", "Experimental", "Contemporary Classical"],
            tuning: "16-NEJI-128",
            mood: ["academic", "complex"],
            tags: ["microtonal", "tone row", "serialism"],
            duration: null,
            album: "Microtonal Serialism Studies",
            bpm: 72,
            key: "Serialist (16-NEJI-128)",
            instruments: ["piano", "synthesizer"],
            description: "A microtonal tone row study using 16-NEJI-128 temperament with serialist compositional techniques",
            dateAdded: "2021-05-26",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_020",
            title: "COVID-19 Sketch",
            artist: "Nick Vuci",
            file: "music/20210528-19NEJI31-COVID19Sketch.mp3",
            year: 2021,
            genre: ["Ambient", "Experimental", "Pandemic Music"],
            tuning: "19-NEJI-31",
            mood: ["anxious", "reflective"],
            tags: ["microtonal", "pandemic", "neji"],
            duration: null,
            album: "Pandemic Reflections",
            bpm: 66,
            key: "19-NEJI-31",
            instruments: ["synthesizer", "electronics"],
            description: "Musical reflection on the COVID-19 pandemic using 19-NEJI-31 temperament",
            dateAdded: "2021-05-28",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_021",
            title: "Anti-Dorian EDM",
            artist: "Nick Vuci",
            file: "music/NickVuci-16edo-Anti_Dorian_EDM.mp3",
            year: 2021,
            genre: ["Electronic Dance", "EDM", "Experimental"],
            tuning: "16-tone equal temperament",
            mood: ["energetic", "danceable"],
            tags: ["microtonal", "edm", "anti-dorian", "dance"],
            duration: null,
            album: "Microtonal EDM",
            bpm: 128,
            key: "Anti-Dorian (16-EDO)",
            instruments: ["synthesizer", "drums", "bass"],
            description: "EDM track using Anti-Dorian mode in 16-EDO with electronic dance beats",
            dateAdded: "2021-04-15",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_022",
            title: "Anti-Ionian EDM",
            artist: "Nick Vuci",
            file: "music/NickVuci-16edo-Anti_Ionian_EDM.mp3",
            year: 2021,
            genre: ["Electronic Dance", "EDM", "Experimental"],
            tuning: "16-tone equal temperament",
            mood: ["uplifting", "danceable"],
            tags: ["microtonal", "edm", "anti-ionian", "dance"],
            duration: null,
            album: "Microtonal EDM",
            bpm: 130,
            key: "Anti-Ionian (16-EDO)",
            instruments: ["synthesizer", "drums", "bass"],
            description: "EDM track using Anti-Ionian mode in 16-EDO with electronic dance beats",
            dateAdded: "2021-04-16",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_023",
            title: "Anti-Locrian EDM",
            artist: "Nick Vuci",
            file: "music/NickVuci-16edo-Anti_Locrian_EDM.mp3",
            year: 2021,
            genre: ["Electronic Dance", "EDM", "Experimental"],
            tuning: "16-tone equal temperament",
            mood: ["tense", "dramatic", "danceable"],
            tags: ["microtonal", "edm", "anti-locrian", "dance"],
            duration: null,
            album: "Microtonal EDM",
            bpm: 126,
            key: "Anti-Locrian (16-EDO)",
            instruments: ["synthesizer", "drums", "bass"],
            description: "EDM track using Anti-Locrian mode in 16-EDO with electronic dance beats",
            dateAdded: "2021-04-18",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_024",
            title: "Anti-Lydian EDM",
            artist: "Nick Vuci",
            file: "music/NickVuci-16edo-Anti_Lydian_EDM.mp3",
            year: 2021,
            genre: ["Electronic Dance", "EDM", "Experimental"],
            tuning: "16-tone equal temperament",
            mood: ["bright", "ethereal", "danceable"],
            tags: ["microtonal", "edm", "anti-lydian", "dance"],
            duration: null,
            album: "Microtonal EDM",
            bpm: 132,
            key: "Anti-Lydian (16-EDO)",
            instruments: ["synthesizer", "drums", "bass"],
            description: "EDM track using Anti-Lydian mode in 16-EDO with electronic dance beats",
            dateAdded: "2021-04-17",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_025",
            title: "Piano Quintet Movement 1 (Draft)",
            artist: "Nick Vuci",
            file: "music/NV-20210420-4567CrossSet-Piano_Quintet_mvmt1_draft.mp3",
            year: 2021,
            genre: ["Chamber Music", "Contemporary Classical", "Cross Set"],
            tuning: "4567 Cross Set",
            mood: ["dramatic", "complex", "emotional"],
            tags: ["microtonal", "chamber music", "piano quintet"],
            duration: null,
            album: "Piano Quintet in Cross Set Temperament",
            bpm: 84,
            key: "Cross Set Tonality",
            instruments: ["piano", "violin", "viola", "cello"],
            description: "First movement draft of a piano quintet composed using 4567 Cross Set temperament",
            dateAdded: "2021-04-20",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_026",
            title: "Lullaby: The Moon Over Lake Ontario",
            artist: "Nick Vuci",
            file: "music/NV-20210424-QuarterCommaMeantone-LullabyThe_Moon_Over_Lake_Ontario.mp3",
            year: 2021,
            genre: ["Folk", "Lullaby", "Historical"],
            tuning: "Quarter-comma meantone",
            mood: ["peaceful", "gentle", "nostalgic"],
            tags: ["historical tuning", "lullaby", "folk"],
            duration: null,
            album: "Historical Tunings",
            bpm: 68,
            key: "G major (Quarter-comma meantone)",
            instruments: ["acoustic guitar", "vocals"],
            description: "A lullaby composed in quarter-comma meantone tuning, inspired by Lake Ontario",
            dateAdded: "2021-04-24",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_027",
            title: "Motherless Child Sketch",
            artist: "Nick Vuci",
            file: "music/NV-20210505-24EDO-MotherlessChildSketch.mp3",
            year: 2021,
            genre: ["Spiritual", "Folk", "Reharmonization"],
            tuning: "24-tone equal temperament",
            mood: ["sorrowful", "haunting"],
            tags: ["microtonal", "spiritual", "folk", "reharmonization"],
            duration: null,
            album: "Microtonal Folk Reharmonizations",
            bpm: 62,
            key: "Minor (24-EDO)",
            instruments: ["piano", "synthesizer"],
            description: "A reharmonization of the spiritual 'Sometimes I Feel Like a Motherless Child' using 24-EDO",
            dateAdded: "2021-05-05",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_028",
            title: "Prelude and Fugue",
            artist: "Nick Vuci",
            file: "music/NV-20210528-4567CrossSet-PreludeAndFugue.mp3",
            year: 2021,
            genre: ["Baroque", "Counterpoint", "Contemporary Classical"],
            tuning: "4567 Cross Set",
            mood: ["intellectual", "intricate"],
            tags: ["microtonal", "baroque", "fugue", "counterpoint"],
            duration: null,
            album: "Microtonal Counterpoint",
            bpm: 90,
            key: "Cross Set Tonality",
            instruments: ["harpsichord", "organ"],
            description: "A baroque-inspired prelude and fugue composed using 4567 Cross Set temperament",
            dateAdded: "2021-05-28",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_029",
            title: "Anti-Ionian Dubstep",
            artist: "Nick Vuci",
            file: "music/NV-20210530-16NEJI128-AntiIonianDubstep.mp3",
            year: 2021,
            genre: ["Electronic", "Dubstep", "Experimental"],
            tuning: "16-NEJI-128",
            mood: ["energetic", "intense"],
            tags: ["microtonal", "dubstep", "neji", "anti-ionian"],
            duration: null,
            album: "Microtonal Dubstep",
            bpm: 140,
            key: "Anti-Ionian (16-NEJI-128)",
            instruments: ["synthesizer", "bass", "drums"],
            description: "Heavy dubstep track using Anti-Ionian mode in 16-NEJI-128 temperament",
            dateAdded: "2021-05-30",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_030",
            title: "Mavila Dubstep",
            artist: "Nick Vuci",
            file: "music/NV-20210530-16NEJI128-MavilaDubstep.flac",
            year: 2021,
            genre: ["Electronic", "Dubstep", "Mavila"],
            tuning: "16-NEJI-128",
            mood: ["dark", "intense"],
            tags: ["microtonal", "dubstep", "mavila", "neji"],
            duration: null,
            album: "Microtonal Dubstep",
            bpm: 142,
            key: "Mavila (16-NEJI-128)",
            instruments: ["synthesizer", "bass", "drums"],
            description: "Heavy dubstep track using Mavila scales in 16-NEJI-128 temperament",
            dateAdded: "2021-05-30",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_031",
            title: "Joyous Thing in 10-EDO",
            artist: "Nick Vuci",
            file: "music/NV-20210728-10EDO-joyous_thing.mp3",
            year: 2021,
            genre: ["Jazz", "Experimental", "World Fusion"],
            tuning: "10-tone equal temperament",
            mood: ["joyful", "uplifting", "energetic"],
            tags: ["microtonal", "10-edo", "jazz", "world"],
            duration: null,
            album: "Explorations in 10-EDO",
            bpm: 98,
            key: "10-EDO Scale",
            instruments: ["marimba", "piano", "percussion"],
            description: "An upbeat, joyful composition exploring the unique sound world of 10-tone equal temperament",
            dateAdded: "2021-07-28",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_032",
            title: "Mohajira Minimalist Prelude",
            artist: "Nick Vuci",
            file: "music/NV-20210728-24EDO-Mohajira7-MinimalistPrelude.mp3",
            year: 2021,
            genre: ["Minimalist", "Middle Eastern", "Contemporary Classical"],
            tuning: "24-tone equal temperament",
            mood: ["meditative", "hypnotic", "flowing"],
            tags: ["microtonal", "minimalist", "mohajira", "middle eastern"],
            duration: null,
            album: "Microtonal Minimalism",
            bpm: 72,
            key: "Mohajira (24-EDO)",
            instruments: ["piano", "synthesizer"],
            description: "A minimalist prelude based on the Mohajira scale in 24-EDO tuning",
            dateAdded: "2021-07-28",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_033",
            title: "Ajde Jano (Yugo Bagpipe)",
            artist: "Nick Vuci",
            file: "music/NV-20210615-Yugo_bagpipe-AjdeJano.mp3",
            year: 2021,
            genre: ["Balkan Folk", "Traditional", "World"],
            tuning: "Yugoslav bagpipe tuning",
            mood: ["lively", "traditional", "festive"],
            tags: ["balkans", "folk", "bagpipe", "traditional"],
            duration: null,
            album: "Balkan Folk Traditions",
            bpm: 108,
            key: "Traditional Balkan",
            instruments: ["bagpipe", "percussion"],
            description: "A traditional Balkan folk tune 'Ajde Jano' performed on Yugoslav bagpipes with traditional tuning",
            dateAdded: "2021-06-15",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_034",
            title: "Maqam Hijaz String Quartet (Movement 1)",
            artist: "Nick Vuci",
            file: "music/NV-20210623-MaqamHijaz-StringQuartet_mvmt1.mp3",
            year: 2021,
            genre: ["Middle Eastern", "Chamber Music", "Contemporary Classical"],
            tuning: "Maqam Hijaz",
            mood: ["evocative", "exotic", "intense"],
            tags: ["maqam", "string quartet", "middle eastern", "hijaz"],
            duration: null,
            album: "String Quartet in Maqamat",
            bpm: 76,
            key: "Maqam Hijaz",
            instruments: ["violin", "viola", "cello"],
            description: "First movement of a string quartet composed using the Maqam Hijaz scale from Middle Eastern music",
            dateAdded: "2021-06-23",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_035",
            title: "Fantasy Intro in 16-EDO",
            artist: "Nick Vuci",
            file: "music/NV-20210820-16edo-FantasyIntro.mp3",
            year: 2021,
            genre: ["Fantasy", "Cinematic", "Orchestral"],
            tuning: "16-tone equal temperament",
            mood: ["epic", "adventurous", "dramatic"],
            tags: ["microtonal", "16-edo", "fantasy", "orchestral"],
            duration: null,
            album: "Microtonal Cinematic Music",
            bpm: 90,
            key: "Fantasy Mode (16-EDO)",
            instruments: ["orchestra", "synthesizer", "percussion"],
            description: "An epic fantasy introduction piece composed in 16-EDO, suitable for film or game soundtrack",
            dateAdded: "2021-08-20",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_036",
            title: "Goblin March",
            artist: "Nick Vuci",
            file: "music/NV-20210820-8edo-GoblinMarch.mp3",
            year: 2021,
            genre: ["Game Music", "Fantasy", "Medieval"],
            tuning: "8-tone equal temperament",
            mood: ["mischievous", "playful", "quirky"],
            tags: ["microtonal", "8-edo", "game music", "goblin"],
            duration: null,
            album: "Microtonal Game Music",
            bpm: 110,
            key: "8-EDO Scale",
            instruments: ["percussion", "recorder", "dulcimer"],
            description: "A quirky goblin march composed in the unusual 8-EDO tuning system, with a medieval fantasy flavor",
            dateAdded: "2021-08-20",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        }
    ],
    // Metadata schema for track validation
    trackSchema: {
        required: ['id', 'title', 'artist', 'file'],
        optional: ['year', 'genre', 'tuning', 'mood', 'tags', 'duration', 'album', 'bpm', 'key', 'instruments', 'description', 'dateAdded', 'playCount', 'lastPlayed', 'favorite', 'waveformData', 'analysisData'],
        types: {
            id: 'string',
            title: 'string',
            artist: 'string',
            file: 'string',
            year: 'number',
            genre: 'array',
            tuning: 'string',
            mood: 'array',
            tags: 'array',
            duration: ['number', 'null'],
            album: ['string', 'null'],
            bpm: ['number', 'null'],
            key: ['string', 'null'],
            instruments: 'array',
            description: 'string',
            dateAdded: 'string',
            playCount: 'number',
            lastPlayed: ['string', 'null'],
            favorite: 'boolean',
            waveformData: ['object', 'null'],
            analysisData: ['object', 'null']
        }
    },

    // Default settings
    defaultVolume: 0.7,
    defaultPlaybackRate: 1.0,
    rememberLastTrack: true,
    
    // Version for data migration
    version: "2.0"
};
