// Additional tracks to be added to tracks.js (tracks 049-138)

        {
            id: "track_049",
            title: "Piano Miniature 2 (24-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20201022-24edo-Miniature2.mp3",
            year: 2020,
            genre: ["Classical Piano", "Minimalist"],
            tuning: "24-tone equal temperament",
            mood: ["contemplative", "delicate", "introspective"],
            tags: ["microtonal", "piano", "24-edo", "miniature"],
            duration: null,
            album: "Quarter-Tone Piano Miniatures",
            bpm: 70,
            key: "24-EDO",
            instruments: ["piano"],
            description: "Second piano miniature in 24 equal divisions of the octave",
            dateAdded: "2020-10-22",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_050",
            title: "Prelude in 16-EDO",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220206-16edo-Prelude.mp3",
            year: 2022,
            genre: ["Classical Piano", "Modern"],
            tuning: "16-tone equal temperment",
            mood: ["contemplative", "flowing", "lyrical"],
            tags: ["microtonal", "piano", "16-edo", "prelude"],
            duration: null,
            album: "16-EDO Piano Works",
            bpm: 85,
            key: "16-EDO",
            instruments: ["piano"],
            description: "A flowing prelude composed in 16 equal divisions of the octave",
            dateAdded: "2022-02-06",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_051",
            title: "Invention in 16-EDO",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220306-16edo-Invention.mp3",
            year: 2022,
            genre: ["Classical Piano", "Baroque Style"],
            tuning: "16-tone equal temperament",
            mood: ["playful", "academic", "precise"],
            tags: ["microtonal", "piano", "16-edo", "invention", "baroque"],
            duration: null,
            album: "16-EDO Piano Works",
            bpm: 110,
            key: "16-EDO",
            instruments: ["piano"],
            description: "A two-part invention in the style of Bach, composed in 16-EDO",
            dateAdded: "2022-03-06",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_052",
            title: "Prelude Sketch in 16-EDO",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220307-16edo-PreludeSketch.mp3",
            year: 2022,
            genre: ["Classical Piano", "Sketch"],
            tuning: "16-tone equal temperament",
            mood: ["exploratory", "tentative", "developing"],
            tags: ["microtonal", "piano", "16-edo", "prelude", "sketch"],
            duration: null,
            album: "16-EDO Piano Works",
            bpm: 80,
            key: "16-EDO",
            instruments: ["piano"],
            description: "A sketch for a prelude in 16-EDO, exploring melodic possibilities",
            dateAdded: "2022-03-07",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_053",
            title: "Prelude 2 Sketch (Electric Piano)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220320-16edo-Prelude2Sketch_EPiano.mp3",
            year: 2022,
            genre: ["Electric Piano", "Jazz", "Modern"],
            tuning: "16-tone equal temperament",
            mood: ["smooth", "jazzy", "experimental"],
            tags: ["microtonal", "electric piano", "16-edo", "prelude", "jazz"],
            duration: null,
            album: "16-EDO Piano Works",
            bpm: 95,
            key: "16-EDO",
            instruments: ["electric piano"],
            description: "A sketch for a second prelude in 16-EDO, performed on electric piano",
            dateAdded: "2022-03-20",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_054",
            title: "Piano Nocturne Draft (5-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220404-5edo-PianoNocturneDraft.mp3",
            year: 2022,
            genre: ["Classical Piano", "Nocturne"],
            tuning: "5-tone equal temperament",
            mood: ["contemplative", "mysterious", "sparse"],
            tags: ["microtonal", "piano", "5-edo", "nocturne", "draft"],
            duration: null,
            album: "Extreme Microtonal Works",
            bpm: 65,
            key: "5-EDO",
            instruments: ["piano"],
            description: "A nocturne draft composed in the highly unusual 5-EDO tuning system",
            dateAdded: "2022-04-04",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_055",
            title: "Free Love by Thoreau (24-EDO Song)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220419-24edo-Song_FreeLoveByThoreau.mp3",
            year: 2022,
            genre: ["Art Song", "Literary", "Vocal"],
            tuning: "24-tone equal temperament",
            mood: ["philosophical", "romantic", "thoughtful"],
            tags: ["microtonal", "24-edo", "thoreau", "art song", "vocal"],
            duration: null,
            album: "Literary Songs",
            bpm: 75,
            key: "24-EDO",
            instruments: ["voice", "piano"],
            description: "A setting of Henry David Thoreau's text about free love, composed in 24-EDO",
            dateAdded: "2022-04-19",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_056",
            title: "War by Vera Brittain (24-EDO Song)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220420-24edo-Song_WarByVeraBrittain.mp3",
            year: 2022,
            genre: ["Art Song", "Literary", "Vocal"],
            tuning: "24-tone equal temperament",
            mood: ["somber", "reflective", "intense"],
            tags: ["microtonal", "24-edo", "vera brittain", "art song", "war"],
            duration: null,
            album: "Literary Songs",
            bpm: 70,
            key: "24-EDO",
            instruments: ["voice", "piano"],
            description: "A setting of Vera Brittain's war poetry, composed in 24-EDO",
            dateAdded: "2022-04-20",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_057",
            title: "Violin Sonata Exposition Sketch (13-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220605-13edo-ViolinSonata_ExpositionSketch.mp3",
            year: 2022,
            genre: ["Chamber Music", "Classical"],
            tuning: "13-tone equal temperament",
            mood: ["academic", "exploratory", "classical"],
            tags: ["microtonal", "13-edo", "violin", "sonata", "sketch"],
            duration: null,
            album: "Chamber Sketches",
            bpm: 100,
            key: "13-EDO",
            instruments: ["violin", "piano"],
            description: "Exposition sketch for a violin sonata in 13 equal divisions of the octave",
            dateAdded: "2022-06-05",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_058",
            title: "Summertime Supermoon (19-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220811-19edo-SummertimeSupermoon.mp3",
            year: 2022,
            genre: ["Ambient", "Atmospheric", "Microtonal"],
            tuning: "19-tone equal temperament",
            mood: ["peaceful", "celestial", "romantic"],
            tags: ["microtonal", "19-edo", "ambient", "supermoon", "summer"],
            duration: null,
            album: "Celestial Microtonal",
            bpm: 60,
            key: "19-EDO",
            instruments: ["synthesizer", "piano", "strings"],
            description: "An atmospheric piece inspired by the summer supermoon, composed in 19-EDO",
            dateAdded: "2022-08-11",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_059",
            title: "Fugue on Theme from Musician Universe Discord (19-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220816-19edo-FugueOnThemeFromMusicianUniverseDiscord.mp3",
            year: 2022,
            genre: ["Classical", "Fugue", "Community"],
            tuning: "19-tone equal temperament",
            mood: ["academic", "collaborative", "complex"],
            tags: ["microtonal", "19-edo", "fugue", "community", "discord"],
            duration: null,
            album: "Community Works",
            bpm: 90,
            key: "19-EDO",
            instruments: ["piano"],
            description: "A fugue based on a theme from the Musician Universe Discord community, in 19-EDO",
            dateAdded: "2022-08-16",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_060",
            title: "Fantasy for Sixth-Tone Harmonium (36-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20220903-36edo-Fantasy_for_Sixth_Tone_Harmonium.mp3",
            year: 2022,
            genre: ["Classical", "Fantasy", "Microtonal"],
            tuning: "36-tone equal temperament",
            mood: ["ethereal", "mystical", "contemplative"],
            tags: ["microtonal", "36-edo", "harmonium", "sixth-tone", "fantasy"],
            duration: null,
            album: "Microtonal Fantasies",
            bpm: 80,
            key: "36-EDO",
            instruments: ["harmonium"],
            description: "A fantasy piece for sixth-tone harmonium, exploring 36 equal divisions of the octave",
            dateAdded: "2022-09-03",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        }
