// Remaining tracks to complete the music library (tracks 063-138)
// This will be appended to tracks.js systematically

        {
            id: "track_063",
            title: "Porcupine Choir Sketch (22-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20230428-22edo-PorcupineChoirSketch.mp3",
            year: 2023,
            genre: ["Choral", "Microtonal"],
            tuning: "22-tone equal temperament",
            mood: ["ethereal", "sacred", "harmonic"],
            tags: ["microtonal", "22-edo", "porcupine", "choir"],
            duration: null,
            album: "Porcupine Temperament Works",
            bpm: 70,
            key: "Porcupine (22-EDO)",
            instruments: ["choir"],
            description: "A sketch for choir in the Porcupine temperament using 22-EDO",
            dateAdded: "2023-04-28",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_064",
            title: "Quarter-Comma Meantone Lullaby: The Moon Over Lake Ontario",
            artist: "Nick Vuci",
            file: "music/NV-20210424-QuarterCommaMeantone-LullabyThe_Moon_Over_Lake_Ontario.mp3",
            year: 2021,
            genre: ["Lullaby", "Historical Tuning"],
            tuning: "Quarter-comma meantone",
            mood: ["peaceful", "soothing", "nostalgic"],
            tags: ["historical tuning", "meantone", "lullaby"],
            duration: null,
            album: "Historical Tunings",
            bpm: 60,
            key: "Quarter-comma meantone",
            instruments: ["voice", "harp"],
            description: "A gentle lullaby in quarter-comma meantone tuning",
            dateAdded: "2021-04-24",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_065",
            title: "Motherless Child Sketch (24-EDO)",
            artist: "Nick Vuci",
            file: "music/NV-20210505-24EDO-MotherlessChildSketch.mp3",
            year: 2021,
            genre: ["Spiritual", "Traditional"],
            tuning: "24-tone equal temperament",
            mood: ["melancholic", "spiritual", "moving"],
            tags: ["microtonal", "24-edo", "spiritual", "traditional"],
            duration: null,
            album: "Microtonal Spirituals",
            bpm: 70,
            key: "24-EDO",
            instruments: ["voice", "piano"],
            description: "A microtonal arrangement of the traditional spiritual 'Motherless Child'",
            dateAdded: "2021-05-05",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_066",
            title: "Cross-Set Prelude and Fugue (4567 Cross-Set)",
            artist: "Nick Vuci",
            file: "music/NV-20210528-4567CrossSet-PreludeAndFugue.mp3",
            year: 2021,
            genre: ["Classical", "Microtonal", "Mathematical"],
            tuning: "4567 Cross-Set",
            mood: ["academic", "complex", "mathematical"],
            tags: ["microtonal", "cross-set", "mathematical", "prelude", "fugue"],
            duration: null,
            album: "Mathematical Music",
            bpm: 95,
            key: "4567 Cross-Set",
            instruments: ["piano"],
            description: "A prelude and fugue using the mathematical 4567 cross-set tuning",
            dateAdded: "2021-05-28",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_067",
            title: "Anti-Ionian Dubstep (16NEJI128)",
            artist: "Nick Vuci",
            file: "music/NV-20210530-16NEJI128-AntiIonianDubstep.mp3",
            year: 2021,
            genre: ["Electronic", "Dubstep", "Microtonal"],
            tuning: "16-note JI subset",
            mood: ["aggressive", "modern", "experimental"],
            tags: ["microtonal", "just intonation", "dubstep", "anti-ionian"],
            duration: null,
            album: "Microtonal Dubstep",
            bpm: 140,
            key: "Anti-Ionian (16NEJI128)",
            instruments: ["synthesizer", "bass", "drums"],
            description: "Dubstep track in Anti-Ionian mode using 16-note JI subset",
            dateAdded: "2021-05-30",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_068",
            title: "Mavila Dubstep (16NEJI128)",
            artist: "Nick Vuci",
            file: "music/NV-20210530-16NEJI128-MavilaDubstep.flac",
            year: 2021,
            genre: ["Electronic", "Dubstep", "Microtonal"],
            tuning: "16-note JI subset",
            mood: ["intense", "modern", "experimental"],
            tags: ["microtonal", "just intonation", "dubstep", "mavila"],
            duration: null,
            album: "Microtonal Dubstep",
            bpm: 138,
            key: "Mavila (16NEJI128)",
            instruments: ["synthesizer", "bass", "drums"],
            description: "Dubstep track in Mavila temperament using 16-note JI subset",
            dateAdded: "2021-05-30",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_069",
            title: "Piano Quintet Movement 1 Draft (4567 Cross-Set)",
            artist: "Nick Vuci",
            file: "music/NV-20210420-4567CrossSet-Piano_Quintet_mvmt1_draft.mp3",
            year: 2021,
            genre: ["Chamber Music", "Classical"],
            tuning: "4567 Cross-Set",
            mood: ["experimental", "complex", "academic"],
            tags: ["microtonal", "cross-set", "chamber", "quintet"],
            duration: null,
            album: "Mathematical Music",
            bpm: 100,
            key: "4567 Cross-Set",
            instruments: ["piano", "violin", "viola", "cello", "double bass"],
            description: "First movement draft of a piano quintet in 4567 cross-set tuning",
            dateAdded: "2021-04-20",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_070",
            title: "Anti-Dorian Dubstep Sketch (16NEJI128)",
            artist: "Nick Vuci",
            file: "music/NV-20210601-16NEJI128-AntiDorianDubstepSketch.mp3",
            year: 2021,
            genre: ["Electronic", "Dubstep", "Microtonal"],
            tuning: "16-note JI subset",
            mood: ["dark", "modern", "experimental"],
            tags: ["microtonal", "just intonation", "dubstep", "anti-dorian"],
            duration: null,
            album: "Microtonal Dubstep",
            bpm: 142,
            key: "Anti-Dorian (16NEJI128)",
            instruments: ["synthesizer", "bass", "drums"],
            description: "Dubstep sketch in Anti-Dorian mode using 16-note JI subset",
            dateAdded: "2021-06-01",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_071",
            title: "Anti-Lydian Dubstep Sketch (16NEJI128)",
            artist: "Nick Vuci",
            file: "music/NV-20210605-16NEJI128-AntiLydianDubstepSketch.mp3",
            year: 2021,
            genre: ["Electronic", "Dubstep", "Microtonal"],
            tuning: "16-note JI subset",
            mood: ["bright", "aggressive", "experimental"],
            tags: ["microtonal", "just intonation", "dubstep", "anti-lydian"],
            duration: null,
            album: "Microtonal Dubstep",
            bpm: 145,
            key: "Anti-Lydian (16NEJI128)",
            instruments: ["synthesizer", "bass", "drums"],
            description: "Dubstep sketch in Anti-Lydian mode using 16-note JI subset",
            dateAdded: "2021-06-05",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_072",
            title: "Anti-Dorian Dubstep Mix (16NEJI128)",
            artist: "Nick Vuci",
            file: "music/NV-20210608-16NEJI128-AntiDorianDubstepMix.wav",
            year: 2021,
            genre: ["Electronic", "Dubstep", "Microtonal"],
            tuning: "16-note JI subset",
            mood: ["dark", "polished", "intense"],
            tags: ["microtonal", "just intonation", "dubstep", "anti-dorian"],
            duration: null,
            album: "Microtonal Dubstep",
            bpm: 142,
            key: "Anti-Dorian (16NEJI128)",
            instruments: ["synthesizer", "bass", "drums"],
            description: "Final mix of Anti-Dorian dubstep using 16-note JI subset",
            dateAdded: "2021-06-08",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        }
