// Continuation of track additions - Batch 2 (tracks 061-100)

        {
            id: "track_061",
            title: "Prelude in 9-EDO",
            artist: "Nick Vuci",
            file: "music/NickVuci-20230331-9edo-Prelude.mp3",
            year: 2023,
            genre: ["Classical Piano", "Microtonal"],
            tuning: "9-tone equal temperament",
            mood: ["mysterious", "angular", "modern"],
            tags: ["microtonal", "9-edo", "piano", "prelude"],
            duration: null,
            album: "Extended Microtonal Works",
            bpm: 75,
            key: "9-EDO",
            instruments: ["piano"],
            description: "A prelude exploring the unusual harmonies of 9 equal divisions of the octave",
            dateAdded: "2023-03-31",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_062",
            title: "Porcupine Prelude 1 (22-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20230426-22edo-PorcupinePrelude1.mp3",
            year: 2023,
            genre: ["Classical Piano", "Microtonal"],
            tuning: "22-tone equal temperament",
            mood: ["contemplative", "flowing", "lyrical"],
            tags: ["microtonal", "22-edo", "porcupine", "prelude"],
            duration: null,
            album: "Porcupine Temperament Works",
            bpm: 85,
            key: "Porcupine (22-EDO)",
            instruments: ["piano"],
            description: "First prelude in the Porcupine temperament using 22-EDO",
            dateAdded: "2023-04-26",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_063",
            title: "Porcupine Choir Sketch (22-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20230428-22edo-PorcupineChoirSketch.mp3",
            year: 2023,
            genre: ["Choral", "Microtonal"],
            tuning: "22-tone equal temperament",
            mood: ["ethereal", "sacred", "harmonic"],
            tags: ["microtonal", "22-edo", "porcupine", "choir", "sketch"],
            duration: null,
            album: "Porcupine Temperament Works",
            bpm: 70,
            key: "Porcupine (22-EDO)",
            instruments: ["choir"],
            description: "A sketch for choir in the Porcupine temperament using 22-EDO",
            dateAdded: "2023-04-28",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_064",
            title: "Semiquartal EDM Draft (14-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20230503-14edo-Semiquartal_EDM_draft.mp3",
            year: 2023,
            genre: ["Electronic", "EDM", "Microtonal"],
            tuning: "14-tone equal temperament",
            mood: ["energetic", "experimental", "modern"],
            tags: ["microtonal", "14-edo", "edm", "semiquartal", "draft"],
            duration: null,
            album: "Experimental EDM",
            bpm: 130,
            key: "14-EDO",
            instruments: ["synthesizer", "drum machine"],
            description: "An experimental EDM piece exploring semiquartal harmony in 14-EDO",
            dateAdded: "2023-05-03",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_065",
            title: "Porcupine Study (22-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20230513-22edo-PorcupineStudy.mp3",
            year: 2023,
            genre: ["Classical Piano", "Study"],
            tuning: "22-tone equal temperament",
            mood: ["academic", "focused", "methodical"],
            tags: ["microtonal", "22-edo", "porcupine", "study"],
            duration: null,
            album: "Porcupine Temperament Works",
            bpm: 95,
            key: "Porcupine (22-EDO)",
            instruments: ["piano"],
            description: "A technical study exploring Porcupine temperament in 22-EDO",
            dateAdded: "2023-05-13",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_066",
            title: "Praeambulum (22-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20230523-22edo-Praeambulum.mp3",
            year: 2023,
            genre: ["Classical Piano", "Baroque Style"],
            tuning: "22-tone equal temperament",
            mood: ["ceremonial", "dignified", "baroque"],
            tags: ["microtonal", "22-edo", "porcupine", "praeambulum", "baroque"],
            duration: null,
            album: "Porcupine Temperament Works",
            bmp: 90,
            key: "Porcupine (22-EDO)",
            instruments: ["piano"],
            description: "A baroque-style praeambulum in Porcupine temperament using 22-EDO",
            dateAdded: "2023-05-23",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_067",
            title: "Porcupine Chorale with Prelude (22-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20230531-22edo-PorcupineChoraleWithPrelude.wav",
            year: 2023,
            genre: ["Choral", "Classical"],
            tuning: "22-tone equal temperament",
            mood: ["sacred", "contemplative", "harmonic"],
            tags: ["microtonal", "22-edo", "porcupine", "chorale", "prelude"],
            duration: null,
            album: "Porcupine Temperament Works",
            bpm: 80,
            key: "Porcupine (22-EDO)",
            instruments: ["choir", "organ"],
            description: "A chorale with prelude in Porcupine temperament using 22-EDO",
            dateAdded: "2023-05-31",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_068",
            title: "Xentimbre Prelude and Fugue (10-EDO, 3L4s)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20230602-10edo-3L4s_XentimbrePreludeAndFugue.mp3",
            year: 2023,
            genre: ["Classical", "Baroque Style"],
            tuning: "10-tone equal temperament",
            mood: ["academic", "complex", "baroque"],
            tags: ["microtonal", "10-edo", "xentimbre", "prelude", "fugue"],
            duration: null,
            album: "Scale Structure Studies",
            bpm: 100,
            key: "3L4s (10-EDO)",
            instruments: ["piano"],
            description: "A prelude and fugue in 3L4s scale structure using 10-EDO",
            dateAdded: "2023-06-02",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_069",
            title: "Xentimbre Canon (13-EDO, 3L4s)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20230603-13edo-3L4s_XentimbreCanon.mp3",
            year: 2023,
            genre: ["Classical", "Canon"],
            tuning: "13-tone equal temperament",
            mood: ["academic", "precise", "counterpoint"],
            tags: ["microtonal", "13-edo", "xentimbre", "canon"],
            duration: null,
            album: "Scale Structure Studies",
            bpm: 85,
            key: "3L4s (13-EDO)",
            instruments: ["piano"],
            description: "A canon in 3L4s scale structure using 13-EDO",
            dateAdded: "2023-06-03",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        },
        {
            id: "track_070",
            title: "Porcupine Chorale 2 (22-EDO)",
            artist: "Nick Vuci",
            file: "music/NickVuci-20230604-22edo-PorcupineChorale2.mp3",
            year: 2023,
            genre: ["Choral", "Classical"],
            tuning: "22-tone equal temperament",
            mood: ["sacred", "peaceful", "harmonic"],
            tags: ["microtonal", "22-edo", "porcupine", "chorale"],
            duration: null,
            album: "Porcupine Temperament Works",
            bpm: 75,
            key: "Porcupine (22-EDO)",
            instruments: ["choir"],
            description: "Second chorale in Porcupine temperament using 22-EDO",
            dateAdded: "2023-06-04",
            playCount: 0,
            lastPlayed: null,
            favorite: false,
            waveformData: null,
            analysisData: null
        }
